"use client";

import { useMemo, useState } from "react";
import { BadgeCheck, Calculator, Info } from "lucide-react";
import type { Locale } from "@/lib/clinic";

export function InstallmentCalculator({ locale }: { locale: Locale }) {
  const [amount,setAmount]=useState(300000); const [months,setMonths]=useState(12); const isRu=locale==="ru";
  const payment=useMemo(()=>Math.ceil(amount/months),[amount,months]);
  const money=(v:number)=>new Intl.NumberFormat(locale==="ru"?"ru-RU":"kk-KZ").format(v)+" ₸";
  return <div className="grid gap-8 rounded-[34px] border border-white/10 bg-white/[.045] p-6 sm:p-9 lg:grid-cols-[1fr_.8fr] lg:p-12"><div><div className="flex items-center gap-3 text-gold"><BadgeCheck/><span className="text-xs font-bold uppercase tracking-[.16em]">Kaspi Red / {isRu?"рассрочка":"бөліп төлеу"}</span></div><h3 className="mt-6 text-3xl font-semibold tracking-[-.04em] sm:text-4xl">{isRu?"Планируйте бюджет спокойно":"Бюджетті жайлы жоспарлаңыз"}</h3><p className="mt-4 max-w-xl leading-7 text-white/52">{isRu?"Калькулятор показывает математическое деление суммы. Участие ABI Dent в программах рассрочки и финальные условия необходимо подтвердить у администратора.":"Калькулятор соманы математикалық түрде бөледі. Бөліп төлеу бағдарламалары мен шарттарын әкімшімен нақтылау қажет."}</p><label className="mt-8 block"><span className="mb-3 flex justify-between text-sm text-white/65"><b>{isRu?"Стоимость лечения":"Емдеу құны"}</b><span>{money(amount)}</span></span><input className="w-full accent-[#d2b678]" type="range" min="50000" max="2000000" step="25000" value={amount} onChange={e=>setAmount(Number(e.target.value))}/></label><div className="mt-7 flex flex-wrap gap-2">{[3,6,12,18,24].map(value=><button key={value} type="button" onClick={()=>setMonths(value)} className={`focus-ring rounded-full border px-4 py-2 text-sm font-bold transition ${months===value?"border-gold bg-gold text-ink":"border-white/15 text-white/60"}`}>{value} {isRu?"мес.":"ай"}</button>)}</div></div><div className="flex flex-col justify-between rounded-[28px] bg-white p-7 text-ink"><Calculator className="text-sapphire" size={30}/><div className="my-9"><p className="text-sm text-slate-500">{isRu?"Ориентировочно в месяц":"Айына шамамен"}</p><p className="mt-2 text-4xl font-semibold tracking-[-.05em]">{money(payment)}</p></div><p className="flex gap-2 text-xs leading-5 text-slate-500"><Info className="mt-0.5 shrink-0" size={14}/>{isRu?"Без учёта комиссий и условий банка. Это не публичная оферта.":"Банк комиссиялары мен шарттарынсыз. Жария оферта емес."}</p></div></div>;
}
